# Extension configuration file.
# Visit the "Extension configuration file (extension.toml)" section for more details:
# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html
#

[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "graph"
title = "ROS2 Lula Inverse Kinematics"
description = "This plugin provides a inverse kinematic solver ros2 node"
authors = ["Michael Habermann Habe6943@vandals.uidaho.edu"]
keywords = ["ROS2", "Inverse Kinematics"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.graph" = {}
"omni.graph.tools" = {}
"isaacsim.ros2.bridge" = {}

# define the Python module that the extension provides
[[python.module]]
name = "ros2_lula_ik"

[settings]
exts."ros2_lula_ik".timeout = 5
